import type { NextPage } from 'next';
import Head from 'next/head';
import { useEffect, useState } from 'react';
import Car from '../types/car';
import Card from '../components/Card';
import Spinner from '../components/Spinner';
import { atEnd } from '../utils/scroll';

const Home: NextPage = () => {
  const [cars, setCars] = useState<Car[]>([]);
  const [load, setLoad] = useState(0);
  const [loading, setLoading] = useState(true);

  const scrolling = () => {
    if (atEnd()) {
      setLoad(load + 1);
      setLoading(true);
    }
  };

  useEffect(() => {
    window.addEventListener('scroll', scrolling, { passive: true });
  });

  useEffect(() => {
    fetch(`/api/cars?next=${cars.length === 0 ? '0' : '1'}`)
      .then((res) => res.json())
      .then((newCars) => {
        setLoading(false);
        setCars((prevCars) => [...prevCars, ...newCars]);
      });
  }, [load]);

  return (
    <div>
      <Head>
        <title>Infinity</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="mt-12 flex justify-center">
        <div>
          <div className="grid lg:grid-cols-4 gap-16">
            {cars.map(({ id, model, make, year, picture }) => (
              <Card
                key={id}
                model={model}
                make={make}
                year={year}
                picture={picture}
              />
            ))}
          </div>
        </div>

        <div className="fixed bottom-5">{loading && <Spinner />}</div>
      </main>
    </div>
  );
};

export default Home;
